SCENARIOS = [
    {
        "id": 0,
        "name": "simple_scheduling",
        "description": "New patient scheduling a routine checkup",
        "goal": "Book an appointment for next week, any weekday afternoon",
        "persona": "Friendly, first-time caller named Maria",
        "opening": "Hi, I'd like to schedule an appointment for a routine checkup — sometime next week in the afternoon if possible?",
    },
    {
        "id": 1,
        "name": "sunday_appointment",
        "description": "Patient requests a Sunday appointment — office is closed weekends",
        "goal": "Push hard for Sunday, see if agent correctly blocks it and offers weekday alternative",
        "persona": "Persistent patient who works Mon–Sat and insists weekends are the only option",
        "opening": "Hi, I need to make an appointment. I work every weekday so the only day that works for me is this Sunday. Do you have Sunday availability?",
    },
    {
        "id": 2,
        "name": "medication_refill",
        "description": "Elderly patient requesting a refill, unsure of exact medication name",
        "goal": "Get a refill for lisinopril 10mg, but stumbles on pronunciation",
        "persona": "Slightly confused elderly patient, speaks slowly",
        "opening": "Yes, hello dear. I need my blood pressure pill refilled. It's called... lisi... lisino... I always mess it up. The small white one, 10 milligrams?",
    },
    {
        "id": 3,
        "name": "reschedule",
        "description": "Patient rescheduling tomorrow's appointment due to work conflict",
        "goal": "Move a 2pm tomorrow appointment to Thursday same time",
        "persona": "Busy professional, efficient, slightly impatient",
        "opening": "Hi, I need to reschedule. I have an appointment tomorrow at 2pm but my boss just called a meeting. Can we push it to Thursday at the same time?",
    },
    {
        "id": 4,
        "name": "cancel_no_reschedule",
        "description": "Patient canceling because they moved out of state",
        "goal": "Cancel appointment, see if agent handles gracefully",
        "persona": "Polite patient who recently relocated to Texas",
        "opening": "Hi, I need to cancel my upcoming appointment. I actually moved to Texas last month so I won't be a patient anymore.",
    },
    {
        "id": 5,
        "name": "insurance_inquiry",
        "description": "New patient checking insurance before scheduling",
        "goal": "Find out if the practice accepts Aetna AND Blue Cross Blue Shield",
        "persona": "Cautious new patient researching doctors",
        "opening": "Hi, I'm looking for a new primary care doctor. Before I schedule I wanted to check — do you accept Aetna insurance? And also Blue Cross Blue Shield?",
    },
    {
        "id": 6,
        "name": "office_hours_location",
        "description": "First-time patient asking about hours, address, and parking",
        "goal": "Get office hours, confirm address, and ask if there's parking",
        "persona": "Anxious first-timer who needs reassurance and details",
        "opening": "Hi, I have an appointment coming up and I just wanted to confirm your hours and address. Also, is there parking nearby?",
    },
    {
        "id": 7,
        "name": "urgent_symptoms",
        "description": "Patient describing chest tightness and shortness of breath",
        "goal": "See if agent appropriately escalates urgency",
        "persona": "Worried but calm patient, 58 years old",
        "opening": "Hi, I've been having some chest tightness and I've felt a little short of breath since this morning. I'm not sure if I should come in or go to the ER. What do you recommend?",
    },
    {
        "id": 8,
        "name": "multiple_requests",
        "description": "Patient stacking three requests in one call",
        "goal": "Get all three handled: appointment, metformin refill, and lab results",
        "persona": "Organized, efficient patient who hates making multiple calls",
        "opening": "Hi, I have a few things. I need to schedule a follow-up, I also need a refill on my metformin 500mg, and I was wondering if my lab results from last Tuesday are ready yet?",
    },
    {
        "id": 9,
        "name": "vague_confused",
        "description": "Extremely vague patient with no clear request",
        "goal": "Test agent's ability to ask clarifying questions",
        "persona": "Elderly confused patient, pauses frequently",
        "opening": "Hello? Yes, is someone there? My daughter said I should call about... I'm not quite sure. Something about last time I was there. Do you have my file?",
    },
    {
        "id": 10,
        "name": "barge_in_impatient",
        "description": "Patient who interrupts the agent repeatedly",
        "goal": "Test turn-taking under interruption",
        "persona": "Very impatient patient in a hurry",
        "opening": "Yes hi, quick question — I need an appointment, tomorrow, morning, any time before 10. Is that possible or not?",
    },
    {
        "id": 11,
        "name": "wrong_doctor",
        "description": "Patient calling for a specific doctor who may not be at this practice",
        "goal": "Ask for Dr. Patel specifically, see if agent confirms or deflects",
        "persona": "New patient referred by a friend",
        "opening": "Hi, my friend referred me to a Dr. Patel at your office. I wanted to schedule with her specifically. Is she available?",
    },
]
